/**
 * SCIS Connect Mobile - Application & API Configuration
 */

export const API_CONFIG = {
  BASE_URL: "https://mca-connect-backend-production.up.railway.app",
  WEB_URL: "https://scisconnect.up.railway.app",
  TIMEOUT_MS: 15000,
  ENDPOINTS: {
    AUTH: {
      LOGIN: "/api/auth/login",
      REFRESH: "/api/auth/refresh",
      FORGOT_PASSWORD: "/api/auth/forgot-password",
      RESET_PASSWORD: "/api/auth/reset-password",
      VERIFY_OTP: "/api/auth/verify-otp",
      ME: "/api/auth/me",
    },
    HOME: {
      DASHBOARD: "/api/dashboard",
    },
    PLACEMENT: {
      LIST: "/api/placements",
    },
    PLACEMENT_CENTER: {
      BASE: "/api/placement",
      DASHBOARD: "/api/placement/dashboard",
      STUDENT_ANALYTICS: "/api/placement/analytics/student",
      JOBS: "/api/placement/jobs",
      APPLICATIONS: "/api/placement/applications/me",
      BOOKMARKS: "/api/placement/bookmarks",
      COLLECTIONS: "/api/placement/collections",
      REMINDERS: "/api/placement/reminders",
      EXPERIENCES: "/api/placement/experiences",
      COMPANIES: "/api/placement/companies",
    },
    NOTIFICATIONS: {
      LIST: "/api/notifications",
      REGISTER_DEVICE: "/api/notifications/register-device",
      UNREGISTER_DEVICE: "/api/notifications/unregister-device",
      PUSH_TOKEN: "/api/notifications/push-token",
      PUSH_EVENTS: "/api/notifications/push-events",
      DELETE: (id: string) => `/api/notifications/${id}`,
      BY_ID: (id: string) => `/api/notifications/${id}`,
    },
    PROFILE: {
      BASE: "/api/profile",
      ME: "/api/profile",
      BY_ID: (userId: string) => `/api/profile/${userId}`,
      COMPLETION: "/api/profile/completion",
      CONTACT: "/api/profile/contact",
      EDUCATION: "/api/profile/education",
      IMAGE: "/api/profile/image",
      PASSWORD: "/api/profile/password",
      PROFESSIONAL: "/api/profile/professional",
      RESUME: "/api/profile/resume",
      RESUME_BY_ID: (resumeId: string) => `/api/profile/resume/${resumeId}`,
      RESUME_PRIMARY: (resumeId: string) => `/api/profile/resume/${resumeId}/primary`,
      RESUME_RENAME: (resumeId: string) => `/api/profile/resume/${resumeId}/rename`,
      SYNC_LEETCODE: "/api/profile/sync-leetcode",
    },
    ALUMNI: {
      SEARCH: "/api/people/search",
      COMPANIES: "/api/people/companies",
      MENTORS: "/api/mentorship/mentors",
      MENTORSHIP_REQUEST: "/api/mentorship",
      MY_REQUESTS: "/api/mentorship/mine",
      POSTS: "/api/posts",
      FORUMS: "/api/forums",
      COMMUNITY_STATS: "/api/community/stats",
      COMMUNITY_SETTINGS: "/api/community-settings",
      FOLLOW: "/api/follow",
    },
    RESULTS: {
      BASE: "/api/results",
      MY_RESULTS: "/api/assessments/results/my",
      MY_RESULT: "/api/results/my-result",
      MY_ALL_RESULTS: "/api/results/my-all-results",
      COMPUTE: "/api/results/compute",
      PUBLISH: "/api/results",
      ANALYSIS: "/api/results/analysis",
      ATTEMPT_ANSWERS: "/api/results/attempt",
      SPEED_ANALYSIS: "/api/results/speed-analysis",
      IMPROVEMENT: "/api/results/improvement",
      SUGGESTIONS: "/api/results/suggestions",
      AI_RECOMMENDATION: "/api/results/ai-recommendation",
      COMPARE: "/api/results/compare",
      GLOBAL_LEADERBOARD: "/api/results/leaderboard/global",
      FILTERED_LEADERBOARD: "/api/results/leaderboard/filtered",
      REPORT_PDF: "/api/results/report/pdf",
      REPORT_CSV: "/api/results/report/csv",
      REPORT_EXCEL: "/api/results/report/excel",
    },
    CHALLENGES: {
      BASE: "/api/challenges",
      MY: "/api/challenges/my",
      GLOBAL_LEADERBOARD: "/api/challenges/leaderboard",
      BY_ID: (id: string) => `/api/challenges/${id}`,
      LEADERBOARD: (id: string) => `/api/challenges/${id}/leaderboard`,
      DAILY_MAX: (id: string, batch?: string) =>
        `/api/challenges/${id}/daily-max${batch ? `?batch=${encodeURIComponent(batch)}` : ""}`,
      JOIN: (id: string) => `/api/challenges/${id}/join`,
      LEAVE: (id: string) => `/api/challenges/${id}/leave`,
    },
    CERTIFICATES: {
      MY: "/api/certificates/my",
      BY_CHALLENGE: (challengeId: string) => `/api/certificates/challenge/${challengeId}`,
      VERIFY: (serial: string) => `/api/certificates/verify/${serial}`,
      VERIFY_WEB: (serial: string) =>
        `https://scisconnect.up.railway.app/certificate/verify/${encodeURIComponent(serial)}`,
    },
    CONTACT: {
      SUBMIT: "/api/contact",
      MY_MESSAGES: "/api/contact/my",
    },
  },
} as const;

export default API_CONFIG;
