import {
  CodingChallenge,
  TestResult,
  LeaderboardEntry,
  PlacementDrive,
  CertificateItem,
} from "./types";

export const MOCK_CHALLENGES: CodingChallenge[] = [
  {
    id: "c1",
    title: "Two Sum & Hash Map Optimizations",
    difficulty: "Easy",
    category: "Arrays & Hashing",
    points: 50,
    acceptanceRate: "89%",
    solved: true,
    tags: ["Array", "Hash Table"],
  },
  {
    id: "c2",
    title: "LRU Cache Implementation",
    difficulty: "Medium",
    category: "Data Structures",
    points: 120,
    acceptanceRate: "64%",
    solved: true,
    tags: ["Doubly Linked List", "Hash Map"],
  },
  {
    id: "c3",
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    category: "Trees & Graphs",
    points: 250,
    acceptanceRate: "42%",
    solved: false,
    tags: ["Tree", "DFS", "Recursion"],
  },
  {
    id: "c4",
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    category: "Binary Search",
    points: 300,
    acceptanceRate: "37%",
    solved: false,
    tags: ["Divide and Conquer", "Binary Search"],
  },
  {
    id: "c5",
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    category: "Dynamic Programming",
    points: 140,
    acceptanceRate: "58%",
    solved: true,
    tags: ["DP", "String"],
  },
];

export const MOCK_TESTS: TestResult[] = [
  {
    id: "t1",
    title: "SCIS Annual Coding Assessment 2026",
    companyOrTopic: "Comprehensive DSA & OOPs",
    date: "Feb 22, 2026",
    score: 92,
    maxScore: 100,
    percentile: 96.4,
    status: "Completed",
    duration: "90 mins",
  },
  {
    id: "t2",
    title: "Full-Stack System Design Mock Round",
    companyOrTopic: "Distributed Systems & REST APIs",
    date: "Feb 15, 2026",
    score: 84,
    maxScore: 100,
    percentile: 88.2,
    status: "Completed",
    duration: "60 mins",
  },
  {
    id: "t3",
    title: "Core CS Aptitude & Logical Reasoning",
    companyOrTopic: "OS, DBMS, CN & Quants",
    date: "Mar 02, 2026",
    score: 0,
    maxScore: 100,
    percentile: 0,
    status: "Upcoming",
    duration: "45 mins",
  },
];

export const MOCK_LEADERBOARD: LeaderboardEntry[] = [
  {
    rank: 1,
    name: "Garv Agrawal",
    rollNo: "24MCME12",
    points: 3420,
    solvedCount: 148,
    batch: "MCA 2024-26",
    isCurrentUser: true,
  },
  {
    rank: 2,
    name: "Ananya Sharma",
    rollNo: "24MCME05",
    points: 3290,
    solvedCount: 139,
    batch: "MCA 2024-26",
  },
  {
    rank: 3,
    name: "Rahul Verma",
    rollNo: "24MCCE18",
    points: 3110,
    solvedCount: 126,
    batch: "IM.Tech 2021-26",
  },
  {
    rank: 4,
    name: "Pooja Reddy",
    rollNo: "24MCMI09",
    points: 2980,
    solvedCount: 118,
    batch: "M.Tech AI 2024-26",
  },
  {
    rank: 5,
    name: "Aditya Kumar",
    rollNo: "24MCMT14",
    points: 2850,
    solvedCount: 112,
    batch: "M.Tech CS 2024-26",
  },
];

export const MOCK_DRIVES: PlacementDrive[] = [
  {
    id: "d1",
    companyName: "Oracle",
    role: "Member Technical Staff (MTS)",
    location: "Hyderabad / Bangalore",
    packageRange: "₹18 - ₹24 LPA",
    eligibility: "CGPA ≥ 7.5 (MCA, M.Tech, IM.Tech)",
    deadline: "Mar 10, 2026",
    status: "Open",
    openings: 8,
    skills: ["Java", "Distributed Systems", "Cloud", "SQL"],
  },
  {
    id: "d2",
    companyName: "Microsoft",
    role: "Software Engineering Intern + FTE",
    location: "Hyderabad",
    packageRange: "₹26 - ₹32 LPA",
    eligibility: "CGPA ≥ 8.0 (All SCIS Programs)",
    deadline: "Mar 05, 2026",
    status: "Closing Soon",
    openings: 5,
    skills: ["C++", "C#", "Data Structures", "Algorithms"],
  },
  {
    id: "d3",
    companyName: "TCS Digital / Prime",
    role: "Systems Engineer (R&D)",
    location: "Pan India",
    packageRange: "₹9 - ₹12 LPA",
    eligibility: "CGPA ≥ 6.5 (No Active Backlogs)",
    deadline: "Mar 15, 2026",
    status: "Open",
    openings: 20,
    skills: ["Python", "Cloud", "Full Stack", "Problem Solving"],
  },
];

export const MOCK_CERTIFICATES: CertificateItem[] = [
  {
    id: "cert1",
    title: "Mastery in Advanced Data Structures & Algorithms",
    issuer: "SCIS Coding Academy",
    issueDate: "Jan 2026",
    credentialId: "SCIS-DSA-2026-9084",
    grade: "Grade A+ (Top 5%)",
    iconName: "ribbon",
  },
  {
    id: "cert2",
    title: "Full Stack Mobile App Engineering (React Native)",
    issuer: "SCIS Innovation Hub",
    issueDate: "Dec 2025",
    credentialId: "SCIS-RN-2025-1102",
    grade: "Verified Distinction",
    iconName: "medal",
  },
  {
    id: "cert3",
    title: "System Design & Distributed Architecture Certification",
    issuer: "University of Hyderabad - SCIS",
    issueDate: "Nov 2025",
    credentialId: "UOH-SCIS-SD-2025",
    grade: "Completed with Honors",
    iconName: "school",
  },
];
